# fluentd.conf (FINAL PRODUCTION VERSION)
<source>
  @type forward
  port 24224
  bind 0.0.0.0
</source>

<filter docker.app.sample>
  @type parser
  key_name log
  reserve_data true
  <parse>
    @type json
  </parse>
</filter>

<match **>
  @type elasticsearch
  host "es01"
  port 9200
  scheme http
  target_es_version "8"
  logstash_format true
  index_name "my-final-docker-logs"
  <buffer>
    @type memory
    flush_interval 1s
  </buffer>
</match>