
# INPUT: Pulling Logs From CLoudTrail S3 Bucket
<source>
  @type s3
  aws_iam_role_arn "#{ENV['AWS_IAM_ROLE_ARN']}"
  s3_region "ap-south-1"
  s3_bucket "aws-cloudtrail-logs-efk-stack-944487268461-1a2815b1"
  s3_object_key_prefix "AWSLogs/944487268461/CloudTrail/"
  pos_file /fluentd/log/s3-cloudtrail-pos.dat
  store_as json
  add_object_metadata true
  tag "cloudtrail.events"
</source>

# FILTER: Parse the nested CloudTrail JSON structure
<filter cloudtail.events>
  @type parser
  key_name message
  reserve_data true
  <parse>
    @type json
    stream_array_key Records
  </parse>
</filter>

# OUTPUT: Send the final, parsed logs to Elasticsearch
<match cloudtrail.events>
  @type elasticsearch
  host "es01"
  port 9200
  scheme http
  index_name "cloudtrail-%Y.%m.%d"
  logstash_format true
  include_tag_key true
  tag_key "@tag"
  <buffer>
    @type memory
    flush_interval 5s
  </buffer>
</match>


